# Generated by Django 6.0.2 on 2026-02-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(blank=True, help_text='Student access end date', null=True),
        ),
    ]
